Feature/article
develhope/Java24-Team2-Spring pull request #2
Opened 2024-05-25 10:13 UTC by ValentinaFo

Creazione entità article e articleValuation con i rispettivi service, controller e repo.

2024-05-25 12:10 UTC, nicolacalisedevelhope requested changes
Migliorare i controlli

2024-05-25 12:10 UTC, nicolacalisedevelhope commented on src/main/java/com/develhope/spring/controllers/ArticleValuationController.java
> +    public ResponseEntity<Void> deleteValuationById(@PathVariable Long id) {
Se non esiste una entity con quell'id che succede ???

2024-05-28 08:40 UTC, ValentinaFo commented on src/main/java/com/develhope/spring/controllers/ArticleValuationController.java
> +    public ResponseEntity<Void> deleteValuationById(@PathVariable Long id) {
Ho modificato

2024-05-29 15:06 UTC, nicolacalisedevelhope approved these changes

2024-05-29 15:06 UTC, merged